from pydantic import BaseModel, Field
import uuid
from typing import Optional, Dict, Any

class EnrollmentRequest(BaseModel):
    bootstrap_token: str = Field(..., description="Short-lived one-time bootstrap token provided during sensor deployment.")
    csr_pem: str = Field(..., description="PEM-encoded Certificate Signing Request generated by the sensor.")
    platform: str = Field(..., description="Operating system platform of the sensor (e.g., Linux, Windows).")
    version: str = Field(..., description="Version of the sensor agent software.")

class EnrollmentResponse(BaseModel):
    sensor_uuid: uuid.UUID = Field(..., description="Cryptographically generated unique identifier for the sensor.")
    tenant_uuid: uuid.UUID = Field(..., description="Tenant identifier this sensor is bound to.")
    client_certificate_pem: str = Field(..., description="Signed client certificate for mTLS.")
    ca_chain_pem: str = Field(..., description="CA certificate chain to trust the server.")
    base_heartbeat_interval: int = Field(60, description="Base interval in seconds for heartbeats.")
    heartbeat_jitter: int = Field(15, description="Jitter in seconds to randomize heartbeat interval.")

class HeartbeatRequest(BaseModel):
    sensor_uuid: uuid.UUID = Field(..., description="Unique identifier of the sensor.")
    status: str = Field(..., description="Current status of the sensor (e.g., ONLINE, DEGRADED).")
    active_honeypots: int = Field(..., description="Number of active honeypots on the sensor.")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Operational metrics (CPU, RAM, etc).")

class HeartbeatResponse(BaseModel):
    acknowledged: bool = Field(True, description="Whether the heartbeat was successfully recorded.")
    config_version: str = Field(..., description="The expected configuration version. If mismatch, sensor should fetch new config.")
    next_heartbeat_base: int = Field(..., description="Base interval for the next heartbeat.")
    next_heartbeat_jitter: int = Field(..., description="Jitter for the next heartbeat.")

class RenewalRequest(BaseModel):
    sensor_uuid: uuid.UUID = Field(..., description="Unique identifier of the sensor.")
    csr_pem: str = Field(..., description="PEM-encoded Certificate Signing Request for the new keypair.")

class RenewalResponse(BaseModel):
    client_certificate_pem: str = Field(..., description="Newly signed client certificate for mTLS.")
