global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: sentinels
    static_configs:
      - targets: ["sentinels:9101"]
        labels:
          service: sentinels

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
